<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\Common\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Social.Common\Social.Common.csproj" />
    <ProjectReference Include="..\Social.Data\Social.Data.csproj" />
    <ProjectReference Include="..\Social.Repository\Social.Repository.Social.User\Social.Repository.Social.User.csproj" />
    <ProjectReference Include="..\Social.Service\Social.Service.Social.Auth\Social.Service.Social.Auth.csproj" />
    <ProjectReference Include="..\Social.Service\Social.Service.Social.Email\Social.Service.Social.Email.csproj" />
    <ProjectReference Include="..\Social.Service\Social.Service.Social.Jwt\Social.Service.Social.Jwt.csproj" />
    <ProjectReference Include="..\Social.Service\Social.Service.Social.File\Social.Service.Social.File.csproj" />
  </ItemGroup>

</Project>
