// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Social.Data.Repository;

#nullable disable

namespace Social.Data.Migrations.Social
{
    [DbContext(typeof(SocialDbContext))]
    [Migration("20260509195057_updateColumnTypeUserPending")]
    partial class updateColumnTypeUserPending
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app_social")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Social.Data.Model.Base.RecordStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status_name")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_record_status");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_record_status_created_by_user_id");

                    b.ToTable("record_status", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.File.FileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_extension")
                        .HasColumnOrder(4);

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasColumnOrder(1);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name")
                        .HasColumnOrder(2);

                    b.Property<string>("FileNameOrigin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name_origin")
                        .HasColumnOrder(3);

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type")
                        .HasColumnOrder(5);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_file_version");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_file_version_created_by_user_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_version_file_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_file_version_reccord_status_id");

                    b.ToTable("file_version", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.File.Files", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_extension")
                        .HasColumnOrder(3);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name")
                        .HasColumnOrder(1);

                    b.Property<string>("FileNameOrigin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name_origin")
                        .HasColumnOrder(2);

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type")
                        .HasColumnOrder(4);

                    b.Property<bool>("FileVersion")
                        .HasColumnType("boolean")
                        .HasColumnName("file_version");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasColumnName("storage_type");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_files_created_by_user_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_files_reccord_status_id");

                    b.ToTable("files", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Notification.Notifications", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid?>("PostCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_comment_id");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_notifications_actor_user_id");

                    b.HasIndex("PostCommentId")
                        .HasDatabaseName("ix_notifications_post_comment_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_notifications_post_id");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.HashTags", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("HashTagName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_tag_name")
                        .HasColumnOrder(1);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.HasKey("Id")
                        .HasName("pk_hash_tags");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_hash_tags_created_by_user_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_hash_tags_reccord_status_id");

                    b.ToTable("hash_tags", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostComments", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasColumnOrder(3);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("like_count");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id")
                        .HasColumnOrder(4);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasColumnOrder(5);

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id")
                        .HasColumnOrder(1);

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("pk_post_comments");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_post_comments_created_by_user_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_comments_post_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_post_comments_reccord_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_post_comments_user_id");

                    b.ToTable("post_comments", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostFiles", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasColumnOrder(2);

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary")
                        .HasColumnOrder(4);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id")
                        .HasColumnOrder(1);

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.HasKey("Id")
                        .HasName("pk_post_files");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_post_files_created_by_user_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_post_files_file_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_files_post_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_post_files_reccord_status_id");

                    b.ToTable("post_files", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostHashTags", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("HashTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("hash_tag_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id")
                        .HasColumnOrder(1);

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.HasKey("Id")
                        .HasName("pk_post_hash_tags");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_post_hash_tags_created_by_user_id");

                    b.HasIndex("HashTagId")
                        .HasDatabaseName("ix_post_hash_tags_hash_tag_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_hash_tags_post_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_post_hash_tags_reccord_status_id");

                    b.ToTable("post_hash_tags", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostLikes", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id")
                        .HasColumnOrder(1);

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("pk_post_likes");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_post_likes_created_by_user_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_likes_post_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_post_likes_reccord_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_post_likes_user_id");

                    b.ToTable("post_likes", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostSaves", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id")
                        .HasColumnOrder(1);

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("pk_post_saves");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_post_saves_created_by_user_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_saves_post_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_post_saves_reccord_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_post_saves_user_id");

                    b.ToTable("post_saves", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostTags", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<float?>("PositionX")
                        .HasColumnType("real")
                        .HasColumnName("positionx");

                    b.Property<float?>("PositionY")
                        .HasColumnType("real")
                        .HasColumnName("positiony");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id")
                        .HasColumnOrder(1);

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("pk_post_tags");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_post_tags_created_by_user_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_tags_post_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_post_tags_reccord_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_post_tags_user_id");

                    b.ToTable("post_tags", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.Post.Posts", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caption")
                        .HasColumnOrder(2);

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasColumnOrder(3);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delete");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("like_count");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("OriginalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_post_id");

                    b.Property<int>("Privacy")
                        .HasColumnType("integer")
                        .HasColumnName("privacy");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<int>("SharedCount")
                        .HasColumnType("integer")
                        .HasColumnName("shared_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_posts_created_by_user_id");

                    b.HasIndex("OriginalPostId")
                        .HasDatabaseName("ix_posts_original_post_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_posts_reccord_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_posts_user_id");

                    b.ToTable("posts", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserFiles", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasColumnOrder(2);

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary")
                        .HasColumnOrder(4);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_user_files");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_user_files_created_by_user_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_user_files_file_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_user_files_reccord_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_files_user_id");

                    b.ToTable("user_files", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserPendingRegistrations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("otp_code");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user_pending_registrations");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_user_pending_registrations_created_by_user_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_user_pending_registrations_reccord_status_id");

                    b.ToTable("user_pending_registrations", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserProfiles", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("address");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth")
                        .HasColumnOrder(5);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name")
                        .HasColumnOrder(3);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name")
                        .HasColumnOrder(2);

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name")
                        .HasColumnOrder(4);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_user_profile");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_user_profile_created_by_user_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_user_profile_reccord_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_profile_user_id");

                    b.ToTable("user_profile", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserRelations", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("FollowerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_user_id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("FollowingUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("following_user_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer")
                        .HasColumnName("relation_type")
                        .HasColumnOrder(3);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("user_relation_status")
                        .HasColumnOrder(4);

                    b.HasKey("Id")
                        .HasName("pk_user_relations");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_user_relations_created_by_user_id");

                    b.HasIndex("FollowerUserId")
                        .HasDatabaseName("ix_user_relations_follower_user_id");

                    b.HasIndex("FollowingUserId")
                        .HasDatabaseName("ix_user_relations_following_user_id");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_user_relations_reccord_status_id");

                    b.ToTable("user_relations", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.User.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<long>("CreatedDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("create_datetime_unix");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified")
                        .HasColumnOrder(6);

                    b.Property<string>("HashText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash_text")
                        .HasColumnOrder(7);

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("KeyResetPassWord")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key_reset_password")
                        .HasColumnOrder(8);

                    b.Property<long?>("KeyResetPassWordExpirationDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("key_reset_password_expiration_date_unix")
                        .HasColumnOrder(9);

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Otp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("otp");

                    b.Property<long?>("OtpExpirationDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("otp_expiration_date_unix");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash")
                        .HasColumnOrder(2);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirm")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_comfirmed")
                        .HasColumnOrder(5);

                    b.Property<int>("RecordStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("reccord_status_id");

                    b.Property<string>("SaltPassWord")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("salt_password")
                        .HasColumnOrder(3);

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token")
                        .HasColumnOrder(10);

                    b.Property<long?>("TokenExpirationDateUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("token_expiration_date_unix")
                        .HasColumnOrder(11);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("user_type");

                    b.Property<bool>("UserLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("user_locked")
                        .HasColumnOrder(4);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_users_created_by_user_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_users_phone_number");

                    b.HasIndex("RecordStatusId")
                        .HasDatabaseName("ix_users_reccord_status_id");

                    b.HasIndex("HashText", "UserName", "PasswordHash")
                        .HasDatabaseName("ix_users_hash_text_user_name_password_hash");

                    b.ToTable("users", "app_social");
                });

            modelBuilder.Entity("Social.Data.Model.File.FileVersion", b =>
                {
                    b.HasOne("Social.Data.Model.File.Files", "Files")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_version_files_file_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_version_record_status_reccord_status_id");

                    b.Navigation("Files");

                    b.Navigation("RecordStatus");
                });

            modelBuilder.Entity("Social.Data.Model.File.Files", b =>
                {
                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_files_record_status_reccord_status_id");

                    b.Navigation("RecordStatus");
                });

            modelBuilder.Entity("Social.Data.Model.Notification.Notifications", b =>
                {
                    b.HasOne("Social.Data.Model.User.Users", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_actor_user_id");

                    b.HasOne("Social.Data.Model.Post.PostComments", "PostComments")
                        .WithMany()
                        .HasForeignKey("PostCommentId")
                        .HasConstraintName("fk_notifications_post_comments_post_comment_id");

                    b.HasOne("Social.Data.Model.Post.Posts", "Posts")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .HasConstraintName("fk_notifications_posts_post_id");

                    b.HasOne("Social.Data.Model.User.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("ActorUser");

                    b.Navigation("PostComments");

                    b.Navigation("Posts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Social.Data.Model.Post.HashTags", b =>
                {
                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hash_tags_record_status_reccord_status_id");

                    b.Navigation("RecordStatus");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostComments", b =>
                {
                    b.HasOne("Social.Data.Model.Post.Posts", "Posts")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_comments_posts_post_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_comments_record_status_reccord_status_id");

                    b.HasOne("Social.Data.Model.User.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_comments_users_user_id");

                    b.Navigation("Posts");

                    b.Navigation("RecordStatus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostFiles", b =>
                {
                    b.HasOne("Social.Data.Model.File.Files", "Files")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_files_files_file_id");

                    b.HasOne("Social.Data.Model.Post.Posts", "Posts")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_files_posts_post_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_files_record_status_reccord_status_id");

                    b.Navigation("Files");

                    b.Navigation("Posts");

                    b.Navigation("RecordStatus");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostHashTags", b =>
                {
                    b.HasOne("Social.Data.Model.Post.HashTags", "HashTags")
                        .WithMany()
                        .HasForeignKey("HashTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_hash_tags_hash_tags_hash_tag_id");

                    b.HasOne("Social.Data.Model.Post.Posts", "Posts")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_hash_tags_posts_post_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_hash_tags_record_status_reccord_status_id");

                    b.Navigation("HashTags");

                    b.Navigation("Posts");

                    b.Navigation("RecordStatus");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostLikes", b =>
                {
                    b.HasOne("Social.Data.Model.Post.Posts", "Posts")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_likes_posts_post_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_likes_record_status_reccord_status_id");

                    b.HasOne("Social.Data.Model.User.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_likes_users_user_id");

                    b.Navigation("Posts");

                    b.Navigation("RecordStatus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostSaves", b =>
                {
                    b.HasOne("Social.Data.Model.Post.Posts", "Posts")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_saves_posts_post_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_saves_record_status_reccord_status_id");

                    b.HasOne("Social.Data.Model.User.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_saves_users_user_id");

                    b.Navigation("Posts");

                    b.Navigation("RecordStatus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Social.Data.Model.Post.PostTags", b =>
                {
                    b.HasOne("Social.Data.Model.Post.Posts", "Posts")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tags_posts_post_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tags_record_status_reccord_status_id");

                    b.HasOne("Social.Data.Model.User.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tags_users_user_id");

                    b.Navigation("Posts");

                    b.Navigation("RecordStatus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Social.Data.Model.Post.Posts", b =>
                {
                    b.HasOne("Social.Data.Model.Post.Posts", "OriginalPost")
                        .WithMany()
                        .HasForeignKey("OriginalPostId")
                        .HasConstraintName("fk_posts_posts_original_post_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_record_status_reccord_status_id");

                    b.HasOne("Social.Data.Model.User.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_users_user_id");

                    b.Navigation("OriginalPost");

                    b.Navigation("RecordStatus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserFiles", b =>
                {
                    b.HasOne("Social.Data.Model.File.Files", "Files")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_files_files_file_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_files_record_status_reccord_status_id");

                    b.HasOne("Social.Data.Model.User.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_files_users_user_id");

                    b.Navigation("Files");

                    b.Navigation("RecordStatus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserPendingRegistrations", b =>
                {
                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_pending_registrations_record_status_reccord_status_id");

                    b.Navigation("RecordStatus");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserProfiles", b =>
                {
                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_record_status_reccord_status_id");

                    b.HasOne("Social.Data.Model.User.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_users_user_id");

                    b.Navigation("RecordStatus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Social.Data.Model.User.UserRelations", b =>
                {
                    b.HasOne("Social.Data.Model.User.Users", "FollowerUsers")
                        .WithMany()
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_relations_users_follower_user_id");

                    b.HasOne("Social.Data.Model.User.Users", "FollowingUsers")
                        .WithMany()
                        .HasForeignKey("FollowingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_relations_users_following_user_id");

                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_relations_record_status_reccord_status_id");

                    b.Navigation("FollowerUsers");

                    b.Navigation("FollowingUsers");

                    b.Navigation("RecordStatus");
                });

            modelBuilder.Entity("Social.Data.Model.User.Users", b =>
                {
                    b.HasOne("Social.Data.Model.Base.RecordStatus", "RecordStatus")
                        .WithMany()
                        .HasForeignKey("RecordStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_record_status_reccord_status_id");

                    b.Navigation("RecordStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
